### ISSUE TITLE
Unable to find my Kubi via bluetooth

### ISSUE THREAD

**Issue by teksbotics** [revolverobotics/KUBI-Video-Issues#2]
Kubi already has on pulsing white light.

Bluetooth on My iPad (iPad Air model A1745) is already turned on.

but cannot find my Kubi.

Please advise.

**Comment by heisian** [comment]
Hello,

From within the Kubi Video app, if you tap the "choose" button on the lower right, do you not see any Kubi listed?

Try holding down the button (you may have to press hard) to reset the Kubi and see if it'll display.

Normally when the white light is pulsing, the Kubi Video app should simply auto-connect when run.  If resetting does not work, there may be a hardware problem with the Kubi.

**Comment by teksbotics** [comment]
Thx.

Actually, suddenly, it is connected. not sure why it wasn't working
yesterday.

Thanks,
Stanley.

-- 
Stanley Seto
司徒展鸿
Director, Teksbotics
+852 63370809
+86 14716032375
----------------
This message (and any attachments) originates from Teksbotics. It may
contain information that is confidential, legally privileged, proprietary,
or otherwise protected by law. The message is intended solely for the named
addressee (or a person responsible for delivering it to the addressee). If
you are not the intended recipient of this message, you are not authorised
to read, print, retain, copy or disseminate this message or any part of it.
If you have received this message in error, please destroy the message or
delete it from your system immediately and notify the sender.

**Comment by heisian** [comment]
Great!
